name: build

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build application
        run:
          meson setup build
          cd ./build
          meson compile